import About, { AboutBox } from "@/components/Home/About";
import Hero from "@/components/Home/Hero";
import Steps from "@/components/Home/Steps";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
      <Steps />
      <div className="w-[90%] mx-auto flex justify-center items-center mt-20">
        <AboutBox
          order
          min={false}
          img="/heroes_rocket.svg"
          heading="Tech stack"
        />
      </div>
    </>
  );
}
